Properties/Properties/Models/PropertiesClass1.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Properties.Models
{
    public class PropertiesClass
    {
        private int id;
        private int squareAcres;
        private int numOfBedrooms;
        private int numOfBathrooms;
        private int propPrice;
        private int numOfFloors;
        private string propType;
        private string location;
        private string country;

        public int Id { get => id; set => id = value; }

        public int SquareAcres { get => squareAcres; set => squareAcres = value; }

        public int NumOfBedrooms { get => numOfBedrooms; set => numOfBedrooms = value; }

        public int NumOfBathrooms { get => numOfBathrooms; set => numOfBathrooms = value; }

        public int PropPrice { get => propPrice; set => propPrice = value; }

        public int NumOfFloors { get => numOfFloors; set => numOfFloors = value; }

        public string PropType { get => propType; set => propType = value; }

        public string Location { get => location; set => location = value; }

        public string Country { get => country; set => country = value; }
    }
}

Properties/Properties/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Properties.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Properties/Properties/Controllers/PropertiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Properties;
using Properties.Models;

namespace Properties.Controllers
{
    public class PropertiesController : Controller
    {
     
        // GET: Properties/Indenx
        public ActionResult Mansion() 
        {       
            var property2 = new PropertiesClass() { Id = 3, SquareAcres = 750, NumOfBathrooms = 25, NumOfBedrooms = 55, NumOfFloors = 8, PropPrice = 5000000, PropType = "Mansion", Location = "Cherbourg", Country = "France" };
            
            return View( property2);
        }

        // GET: Properties/DetachedHouse
        public ActionResult DetachedHouse()
        {
            var property = new PropertiesClass() { Id = 1, SquareAcres = 300, NumOfBathrooms = 4, NumOfBedrooms = 8, NumOfFloors = 3, PropPrice = 75000, PropType = "House", Location = "Kent", Country = "United kingdom" };
            return View(property);
        }

        // GET: Properties/SemiDetachedHouse
        public ActionResult SemiDetachedHouse()
        {
            var property1 = new PropertiesClass() { Id = 2, SquareAcres = 100, NumOfBathrooms = 1, NumOfBedrooms = 2, NumOfFloors = 2, PropPrice = 250000, PropType = "Semi-detached House", Location = "Liverpool", Country = "United kingdom" };
            return View(property1);
        }

        public ActionResult Listings()
        {

            return View();
        }

        public ActionResult NewListings(/*string username, int? password*/)
        {
            //if (username == "Tevin" && password == 123)
            //{
            //    return View();
            //}
            //return View("The user with the username " + username + " " + "and password do not match");
            return View();
        }

        /*[Route("Viewings/opendates/{year}/{month:regex(\\d{4}):range(1-12)}")]*/
        //public ActionResult PropertiesViews(int year, int month)
        //{


        //    return View();
        //}
    }
}

Properties/Properties/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Properties/Properties/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Properties/Properties/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Property Listings</h1>
    <p class="lead">Property Listings is a free web framework for building great Property Sales Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
	<div class="col-md-3">
		<h2>Getting started</h2>
		<p>
			ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
			enables a clean separation of concerns and gives you full control over markup
			for enjoyable, agile development.
		</p>
		<p><a class="btn btn-default" href="/">Learn more &raquo;</a></p>
	</div>
	<div class="col-md-3">
		<h2>Get more libraries</h2>
		<p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
		<p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
	</div>
	<div class="col-md-3">
		<h2>Web Hosting</h2>
		<p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
		<p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
	</div>
	<div col-md-3>
		@using (Html.BeginForm("NewListings", "Properties", FormMethod.Post))
		{
			@Html.Label("", "Enter UserName")<br />
			@Html.TextBox("Username", "")<br />

			@Html.Label("", "Enter Password")<br />
			@Html.Password("Enter Password", "")<br />

			<input type="submit" />
		}
	</div>
</div>

Properties/Properties/Views/Properties/DetachedHouse.cshtml
@model Properties.Models.PropertiesClass
@{
    ViewBag.Title = "DetachedHouse";
}

<h2>DetachedHouse</h2>

<h2>
	Id:@Model.Id <br />
	Country:@Model.Country <br />
	Location:@Model.Location<br />
	Type:@Model.PropType<br />
	Price:@Model.PropPrice <br />
	Bedrooms:@Model.NumOfBedrooms <br />
	Bathrooms:@Model.NumOfBathrooms <br />
	Floors:@Model.NumOfFloors<br />
	Acres ^2:@Model.SquareAcres <br />
</h2>

Properties/Properties/Views/Properties/Listings.cshtml
@model Properties.Models.PropertiesClass
@{
	ViewBag.Title = "Listings";
}

<h2>Viewings</h2>

<li>@Html.ActionLink("Mansion", "Mansion", "Properties")</li>
<li>@Html.ActionLink("House", "DetachedHouse", "Properties")</li>
<li>@Html.ActionLink("House", "SemiDetachedHouse", "Properties")</li>

@*<h2>
	Id:@Model.Id <br />
	Country:@Model.Country <br />
	Location:@Model.Location<br />
	Acres ^2:@Model.SquareAcres <br />
	Price:@Model.PropPrice <br />
	Type:@Model.PropType<br />
	Bedrooms:@Model.NumOfBedrooms <br />
	Bathrooms:@Model.NumOfBathrooms <br />
	Floors:@Model.NumOfFloors<br />

</h2>*@

Properties/Properties/Views/Properties/Mansion.cshtml
@model  Properties.Models.PropertiesClass
@{
	ViewBag.Title = "Index";
}

 
@*<h2>
	@Model.Country
	@Model.Id
	@Model.Location
	@Model.NumOfBathrooms
	@Model.NumOfBedrooms
	@Model.NumOfFloors
	@Model.PropPrice
	@Model.PropType
	@Model.SquareAcres

</h2>*@
<h1>Mansion</h1>
<h2>
	Id:@Model.Id <br />
	Country:@Model.Country <br />
	Location:@Model.Location<br />
	Type:@Model.PropType<br />
	Price:@Model.PropPrice <br />
	Bedrooms:@Model.NumOfBedrooms <br />
	Bathrooms:@Model.NumOfBathrooms <br />
	Floors:@Model.NumOfFloors<br />
	Acres ^2:@Model.SquareAcres <br />
</h2>

Properties/Properties/Views/Properties/NewListings.cshtml
@model Properties.Models.PropertiesClass

@{
    ViewBag.Title = "View";
}

<h2>View</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Property Management</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SquareAcres, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SquareAcres, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SquareAcres, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumOfBedrooms, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumOfBedrooms, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumOfBedrooms, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumOfBathrooms, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumOfBathrooms, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumOfBathrooms, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PropPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PropPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PropPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumOfFloors, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumOfFloors, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumOfFloors, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PropType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PropType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PropType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Listings")
</div>

Properties/Properties/Views/Properties/SemiDetachedHouse.cshtml
@model  Properties.Models.PropertiesClass
@{
	ViewBag.Title = "SemiDetachedHouse";
}

<h2>SemiDetachedHouse</h2>

<h2>
	Id:@Model.Id <br />
	Country:@Model.Country <br />
	Location:@Model.Location<br />
	Type:@Model.PropType<br />
	Price:@Model.PropPrice <br />
	Bedrooms:@Model.NumOfBedrooms <br />
	Bathrooms:@Model.NumOfBathrooms <br />
	Floors:@Model.NumOfFloors<br />
	Acres ^2:@Model.SquareAcres <br />
</h2>

Properties/Properties/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li>@Html.ActionLink("Home", "Index", "Home")</li>
					<li>@Html.ActionLink("About", "About", "Home")</li>
					<li>@Html.ActionLink("Contact", "Contact", "Home")</li>
					<li>@Html.ActionLink("Listings", "Listings", "Properties")</li>
					<li>
						@Html.ActionLink("Login", "NewListings", "Properties")
					</li>
				</ul>
				
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>